<x-student-layout title="My Attendance">
 <x-student-absence-warning :warnings="$subjectAbsenceWarnings" />
 <section x-data="{ date: '', subject: '', status: '' }">
  <div class="mb-5"><h2 class="text-lg font-semibold text-slate-900">Attendance history</h2><p class="mt-1 text-sm text-slate-500">Official records are maintained by the administration.</p></div>
  @php $subjects = $logs->getCollection()->map(fn($log) => $log->schedule?->subject)->filter()->unique('id')->sortBy('subject_code'); @endphp
  <div class="mb-5 border border-slate-200 bg-white p-4"><div class="grid gap-4 sm:grid-cols-3">
   <label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Date<input x-model="date" type="date" class="mt-1.5 block w-full rounded-md border-slate-300 text-sm focus:border-teal-600 focus:ring-teal-600"></label>
   <label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Subject<select x-model="subject" class="mt-1.5 block w-full rounded-md border-slate-300 text-sm focus:border-teal-600 focus:ring-teal-600"><option value="">All subjects</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->subject_code }} — {{ $subject->subject_name }}</option>@endforeach</select></label>
   <label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Status<select x-model="status" class="mt-1.5 block w-full rounded-md border-slate-300 text-sm focus:border-teal-600 focus:ring-teal-600"><option value="">All statuses</option>@foreach(['present','late','absent','excused'] as $option)<option value="{{ $option }}">{{ ucfirst($option) }}</option>@endforeach</select></label>
  </div><button x-show="date || subject || status" @click="date=''; subject=''; status=''" class="mt-3 text-xs font-semibold text-teal-700">Clear filters</button></div>
  <div class="hidden overflow-hidden border border-slate-200 bg-white md:block"><table class="w-full text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3.5">Date</th><th class="px-5 py-3.5">Subject</th><th class="px-5 py-3.5">Schedule</th><th class="px-5 py-3.5">Time scanned</th><th class="px-5 py-3.5">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($logs as $log) @php $scan=\Illuminate\Support\Carbon::parse($log->scan_time); $schedule=$log->schedule; @endphp<tr x-show="(!date || date === '{{ $scan->format('Y-m-d') }}') && (!subject || subject === '{{ $schedule?->subject?->id }}') && (!status || status === '{{ strtolower($log->status) }}')"><td class="whitespace-nowrap px-5 py-4">{{ $scan->format('M d, Y') }}</td><td class="px-5 py-4"><p class="font-semibold text-slate-800">{{ $schedule?->subject?->subject_code ?? '—' }}</p><p class="text-xs text-slate-500">{{ $schedule?->subject?->subject_name ?? 'Subject unavailable' }}</p></td><td class="whitespace-nowrap px-5 py-4 text-slate-600">@if($schedule){{ ucfirst($schedule->day) }}<br><span class="text-xs">{{ \Illuminate\Support\Carbon::parse($schedule->start_time)->format('g:i A') }} – {{ \Illuminate\Support\Carbon::parse($schedule->end_time)->format('g:i A') }}</span>@else—@endif</td><td class="whitespace-nowrap px-5 py-4">{{ $scan->format('g:i A') }}<br><span class="text-xs capitalize text-slate-500">{{ str_replace('_',' ',$log->attendance_type) }}</span></td><td class="px-5 py-4"><x-student-status :status="$log->status" /></td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-500">No attendance records yet.</td></tr>@endforelse</tbody></table></div>
  <div class="divide-y divide-slate-200 border border-slate-200 bg-white md:hidden">@forelse($logs as $log) @php $scan=\Illuminate\Support\Carbon::parse($log->scan_time); $schedule=$log->schedule; @endphp<article x-show="(!date || date === '{{ $scan->format('Y-m-d') }}') && (!subject || subject === '{{ $schedule?->subject?->id }}') && (!status || status === '{{ strtolower($log->status) }}')" class="p-4"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold text-teal-800">{{ $schedule?->subject?->subject_code ?? '—' }}</p><h3 class="text-sm font-semibold">{{ $schedule?->subject?->subject_name ?? 'Subject unavailable' }}</h3></div><x-student-status :status="$log->status" /></div><dl class="mt-3 grid grid-cols-2 gap-2 text-xs"><div><dt class="text-slate-400">Date</dt><dd class="mt-0.5">{{ $scan->format('M d, Y') }}</dd></div><div><dt class="text-slate-400">Time scanned</dt><dd class="mt-0.5">{{ $scan->format('g:i A') }}</dd></div><div class="col-span-2"><dt class="text-slate-400">Schedule</dt><dd class="mt-0.5">{{ $schedule ? ucfirst($schedule->day).' · '.\Illuminate\Support\Carbon::parse($schedule->start_time)->format('g:i A') : '—' }}</dd></div></dl></article>@empty<div class="py-12 text-center text-sm text-slate-500">No attendance records yet.</div>@endforelse</div>
  @if($logs->hasPages())<div class="mt-5">{{ $logs->withQueryString()->links() }}</div>@endif
 </section>
</x-student-layout>
