<x-student-layout title="Dashboard">
 @unless(Auth::user()->isAccountActive())<div class="mb-6 border-l-4 border-red-500 bg-red-50 px-4 py-3 text-sm font-medium text-red-800">Attendance is unavailable because your account is inactive. Please contact the administrator.</div>@endunless
 <x-student-absence-warning :warnings="$subjectAbsenceWarnings" />
 <section class="border border-slate-200 bg-white px-5 py-5 sm:px-6"><p class="text-sm font-medium text-teal-700">{{ now()->format('l, F j, Y') }}</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 18 ? 'afternoon' : 'evening') }}, {{ $student->first_name }}</h2><p class="mt-1 text-sm text-slate-600"><span class="font-medium">{{ $student->course?->course_code ?? 'Course not assigned' }}@if($student->section) {{ $student->section->section_name }}@endif</span>@if($student->course?->department)<span class="mx-2 text-slate-300">|</span>{{ $student->course->department->department_name }}@endif</p></section>
 <section class="mt-6 border-y border-slate-200 bg-white" aria-labelledby="summary-title"><div class="px-5 pt-4"><h2 id="summary-title" class="text-sm font-semibold text-slate-800">Attendance summary</h2><p class="text-xs text-slate-500">All recorded attendance</p></div><div class="mt-3 grid grid-cols-2 divide-x divide-y divide-slate-200 sm:grid-cols-4 sm:divide-y-0">@foreach(['present'=>'bg-emerald-500','late'=>'bg-amber-500','absent'=>'bg-red-500','excused'=>'bg-sky-500'] as $status=>$dot)<div class="px-5 py-4"><div class="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-500"><span class="h-2 w-2 rounded-full {{ $dot }}"></span>{{ $status }}</div><p class="mt-2 text-2xl font-semibold text-slate-900">{{ $stats[$status] }}</p></div>@endforeach</div></section>
 <div class="mt-7 grid items-start gap-7 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.8fr)]">
  <section id="schedule" class="scroll-mt-24"><div class="mb-4 flex items-end justify-between"><div><h2 class="text-lg font-semibold text-slate-900">Weekly schedule</h2><p class="mt-0.5 text-sm text-slate-500">Your classes by day and time</p></div><span class="text-xs font-medium text-slate-400">{{ $schedules->count() }} {{ Str::plural('class', $schedules->count()) }}</span></div>
   @if($schedules->isEmpty())<div class="border border-dashed border-slate-300 bg-white py-12 text-center text-sm text-slate-500">{{ $student->section ? 'No schedule found for your section.' : "You haven't been assigned to a section yet." }}</div>@else
   <div class="border border-slate-200 bg-white">@foreach($dayOrder as $day) @if($scheduleByDay->has($day))<div class="grid border-b border-slate-200 last:border-b-0 md:grid-cols-[120px_1fr]"><div class="bg-slate-50 px-4 py-4 text-xs font-semibold uppercase tracking-wider text-teal-800">{{ ucfirst($day) }}</div><div class="divide-y divide-slate-100">@foreach($scheduleByDay[$day] as $item)<article class="grid gap-3 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div class="min-w-0"><div class="flex flex-wrap items-baseline gap-x-2"><p class="text-sm font-bold text-teal-800">{{ $item->subject?->subject_code ?? '—' }}</p><h3 class="text-sm font-semibold text-slate-900">{{ $item->subject?->subject_name ?? 'Subject unavailable' }}</h3></div><p class="mt-1 text-xs text-slate-500">{{ trim(($item->instructor?->first_name ?? '').' '.($item->instructor?->last_name ?? '')) ?: 'Instructor not assigned' }}<span class="mx-1.5 text-slate-300">•</span>{{ $item->room ?: 'Room TBA' }}</p></div><div class="text-left sm:text-right"><p class="whitespace-nowrap text-sm font-medium text-slate-700">{{ \Illuminate\Support\Carbon::parse($item->start_time)->format('g:i A') }} – {{ \Illuminate\Support\Carbon::parse($item->end_time)->format('g:i A') }}</p></div></article>@endforeach</div></div>@endif @endforeach</div>@endif
  </section>
  <section><div class="mb-4 flex items-end justify-between"><div><h2 class="text-lg font-semibold text-slate-900">Recent attendance</h2><p class="mt-0.5 text-sm text-slate-500">Latest scan records</p></div><a href="{{ route('student.attendance') }}" class="text-sm font-semibold text-teal-700 hover:text-teal-900">View all</a></div>
   <div class="border border-slate-200 bg-white">@forelse($myAttendance as $log)<article class="border-b border-slate-100 px-4 py-4 last:border-0"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="text-xs font-bold text-teal-800">{{ $log->schedule?->subject?->subject_code ?? '—' }}</p><p class="truncate text-sm font-medium text-slate-800">{{ $log->schedule?->subject?->subject_name ?? 'Subject unavailable' }}</p></div><x-student-status :status="$log->status" /></div><div class="mt-2 flex flex-wrap gap-x-3 text-xs text-slate-500"><span>{{ \Illuminate\Support\Carbon::parse($log->scan_time)->format('F j, Y') }}</span><span>{{ \Illuminate\Support\Carbon::parse($log->scan_time)->format('g:i A') }}</span><span class="capitalize">{{ str_replace('_',' ',$log->attendance_type) }}</span></div></article>@empty<div class="py-12 text-center text-sm text-slate-500">No attendance records yet.</div>@endforelse</div>
  </section>
 </div>
</x-student-layout>
