<x-instructor-layout title="Profile">
<div class="mb-6"><h2 class="text-xl font-semibold">My Profile</h2><p class="text-sm text-slate-500">Manage your profile photo and account security.</p></div>
<form method="POST" action="{{ route('my-profile.update') }}" enctype="multipart/form-data" class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200/70">@csrf @method('PATCH')
<div class="h-2 bg-gradient-to-r from-indigo-600 to-violet-600"></div>
<div class="flex flex-col gap-5 border-b border-slate-100 p-6 sm:flex-row sm:items-center">
    <div x-data="{preview:@js($user->avatar_url),objectUrl:null}" class="flex items-center gap-5"><div class="h-24 w-24 overflow-hidden rounded-full bg-indigo-100 text-indigo-700 ring-4 ring-white shadow-md"><img x-show="preview" :src="preview" class="h-full w-full object-cover" alt="Profile preview"><div x-show="!preview" class="grid h-full place-items-center text-3xl font-semibold">{{ strtoupper(substr($user->name,0,1)) }}</div></div><div><label for="avatar" class="inline-flex cursor-pointer rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">Change photo</label><input id="avatar" name="avatar" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=$event.target.files[0]?URL.createObjectURL($event.target.files[0]):null;preview=objectUrl||@js($user->avatar_url)"><p class="mt-2 text-xs text-slate-500">JPG, PNG, or WebP. Maximum 2 MB.</p>@error('avatar')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div></div>
    <div class="sm:ml-auto sm:text-right">
        <p class="text-lg font-semibold">{{ $user->instructor?->fullName() ?? $user->name }}</p>
        <p class="text-sm text-slate-500">Teaching Personnel</p>
        <div class="mt-2 flex items-center gap-2 sm:justify-end"><span class="text-xs font-medium text-slate-500">Account Status</span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $user->isAccountActive() ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700' }}">{{ ucfirst($user->status) }}</span></div>
        @unless ($user->isAccountActive())<p class="mt-2 text-sm text-red-600">Attendance is disabled. Please contact the administrator.</p>@endunless
    </div>
</div>
<div class="grid gap-8 p-6 lg:grid-cols-2">
<section><h3 class="font-semibold">Personal information</h3><p class="mt-1 text-sm text-slate-500">Employee information is read-only.</p><div class="mt-5 space-y-4"><div><x-input-label for="name" value="Account name"/><x-text-input id="name" name="name" class="mt-1 block w-full" :value="old('name',$user->name)" required/><x-input-error class="mt-2" :messages="$errors->get('name')"/></div><div><x-input-label for="email" value="Email"/><x-text-input id="email" name="email" type="email" class="mt-1 block w-full" :value="old('email',$user->email)" required/><x-input-error class="mt-2" :messages="$errors->get('email')"/></div><div class="grid gap-4 sm:grid-cols-2"><div><x-input-label value="Employee ID"/><p class="mt-1 rounded-xl bg-slate-50 px-3 py-2 text-sm">{{ $user->instructor?->employee_no ?? '—' }}</p></div><div><x-input-label value="Department"/><p class="mt-1 rounded-xl bg-slate-50 px-3 py-2 text-sm">{{ $user->instructor?->department?->department_name ?? '—' }}</p></div></div></div></section>
<section><h3 class="font-semibold">Change password</h3><p class="mt-1 text-sm text-slate-500">Leave blank to retain your current password.</p><div class="mt-5 space-y-4"><div><x-input-label for="current_password" value="Current password"/><x-text-input id="current_password" name="current_password" type="password" class="mt-1 block w-full"/><x-input-error class="mt-2" :messages="$errors->get('current_password')"/></div><div><x-input-label for="password" value="New password"/><x-text-input id="password" name="password" type="password" class="mt-1 block w-full"/><x-input-error class="mt-2" :messages="$errors->get('password')"/></div><div><x-input-label for="password_confirmation" value="Confirm password"/><x-text-input id="password_confirmation" name="password_confirmation" type="password" class="mt-1 block w-full"/></div></div></section>
</div><div class="flex justify-end border-t border-slate-100 bg-slate-50 px-6 py-4"><x-primary-button>Save changes</x-primary-button></div></form>
</x-instructor-layout>
