<x-app-layout>
<x-slot name="header"><h2 class="text-xl font-semibold">Scanner Security</h2></x-slot>
<div class="space-y-8 p-6">
<section class="rounded-xl bg-white p-6 shadow"><h3 class="text-lg font-bold">Registered terminals</h3>
<form method="POST" action="{{ route('scanner-security.terminals.store') }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf<input name="name" placeholder="Terminal name" required><input name="location" placeholder="Trusted location" required><button class="rounded bg-indigo-600 px-4 py-2 text-white">Register terminal</button></form>
<div class="mt-5 space-y-3">@forelse($terminals as $terminal)<form method="POST" action="{{ route('scanner-security.terminals.update',$terminal) }}" class="grid gap-2 border-t pt-3 md:grid-cols-4">@csrf @method('PATCH')<input name="name" value="{{ $terminal->name }}" required><input name="location" value="{{ $terminal->location }}" required><select name="is_active"><option value="1" @selected($terminal->is_active)>Active</option><option value="0" @selected(!$terminal->is_active)>Inactive</option></select><button class="rounded border px-3 py-2">Save</button></form>@empty<p class="text-gray-500">No terminals registered.</p>@endforelse</div></section>
<section class="rounded-xl bg-white p-6 shadow"><h3 class="text-lg font-bold">Revoke and replace a QR card</h3><p class="mt-1 text-sm text-gray-500">The current random credential is revoked immediately. Download and issue the replacement ID card afterward.</p><form method="POST" x-data="{user:''}" :action="'{{ url('scanner-security/users') }}/'+user+'/qr/regenerate'" class="mt-4 flex gap-3">@csrf<select x-model="user" required class="flex-1"><option value="">Select user</option>@foreach($qrUsers as $u)<option value="{{ $u->id }}">{{ $u->name }} ({{ $u->role?->role_name }})</option>@endforeach</select><button :disabled="!user" onclick="return confirm('Revoke this user’s current QR and issue a replacement?')" class="rounded bg-red-600 px-4 py-2 text-white disabled:opacity-50">Revoke and regenerate</button></form></section>
<section class="rounded-xl bg-white p-6 shadow"><h3 class="text-lg font-bold">Security flags</h3><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Detected</th><th>Severity</th><th>Category</th><th>Evidence</th><th>Status</th></tr></thead><tbody>@forelse($flags as $flag)<tr class="border-t"><td>{{ $flag->detected_at }}</td><td>{{ $flag->severity }}</td><td>{{ str($flag->category)->replace('_',' ')->title() }}</td><td>{{ $flag->evidence }}</td><td><form method="POST" action="{{ route('scanner-security.flags.update',$flag) }}">@csrf @method('PATCH')<select name="status" onchange="this.form.submit()">@foreach(['open','reviewed','confirmed','dismissed'] as $s)<option @selected($flag->status===$s)>{{ $s }}</option>@endforeach</select></form></td></tr>@empty<tr><td colspan="5" class="py-5 text-gray-500">No security flags.</td></tr>@endforelse</tbody></table></div>{{ $flags->links() }}</section>
<section class="rounded-xl bg-white p-6 shadow"><h3 class="text-lg font-bold">Immutable scan audit trail</h3><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Time</th><th>Outcome</th><th>User</th><th>Admin</th><th>Terminal</th><th>Location</th><th>IP</th></tr></thead><tbody>@foreach($audits as $audit)<tr class="border-t"><td>{{ $audit->created_at }}</td><td>{{ $audit->outcome }}</td><td>{{ $audit->user_id ?? '—' }}</td><td>{{ $audit->admin_id ?? '—' }}</td><td>{{ $audit->scanner_terminal_id ?? '—' }}</td><td>{{ $audit->location ?? '—' }}</td><td>{{ $audit->ip_address ?? '—' }}</td></tr>@endforeach</tbody></table></div>{{ $audits->links() }}</section>
</div></x-app-layout>
